spring:
  data:
    mongodb:
      dataBase: library_db
      port: 27017
      host: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  file:
    path: "/logs"
    name: "debug-log.txt"
  logback:
    rollingpolicy:
      max-file-size: 10
      file-name-pattern: "logs/spring-boot-logger-%d{yyyy-MM-dd_HH-mm}.%i.log"
  level:
    console:
      root: debug
    file:
      root: debug
  charset:
    console: UTF-8
    file: UTF-8

#mongock:
#    runner-type: "ApplicationRunner" # default
#  runner-type: "InitializingBean"
#  change-logs-scan-package:
#    - ru.otus.spring.mongock.changelog672758