spring:
  data:
    :mongodb:
      dataBase: library_db
      port: 0
      host: localhost

mongock:
  #  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog672758

hystrix:
  command:
    ck:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000